name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.3
      id: version
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION"
        
#    - name: Build docker image
#      run: |
#        docker build -t chrdevelop/docker-graphql:0.0.2 .
#        docker build -t chrdevelop/docker-graphql:latest .

#    - name: Push docker image
#      run: |
#        docker push chrdevelop/docker-graphql:0.0.2
#        docker push chrdevelop/docker-graphql:latest
  
